'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pCarrelloConsegna

    '''<summary>
    '''IframecarreloStp3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IframecarreloStp3 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PannelloDinamico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PannelloDinamico As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rdoCorr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoCorr As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlSelectIndirizzo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSelectIndirizzo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlIndirizzo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIndirizzo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lnkAddInd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddInd As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''pnlIndRitiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIndRitiro As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblInfoCorr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoCorr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataCons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataCons As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlTrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTrace As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtTrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTrace As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lnkMiaMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMiaMail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblErrEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnScegliPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnScegliPagamento As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''carrelloHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents carrelloHelp As Global.FormerWeb.ucCarrelloHelp

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
End Class
