'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pCarrelloRiepilogo

    '''<summary>
    '''IframecarreloStp5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IframecarreloStp5 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rptOrdini control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptOrdini As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnOrdina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrdina As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''carrelloHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents carrelloHelp As Global.FormerWeb.ucCarrelloHelp
End Class
