'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pProdotto

    '''<summary>
    '''AlberoPreventivazioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlberoPreventivazioni As Global.FormerWeb.ucPreventivazioni

    '''<summary>
    '''PannelloDinamico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PannelloDinamico As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''iframeRefactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iframeRefactor As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFormato As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkMisurePersonalizzate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMisurePersonalizzate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlMisurePersonalizzate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMisurePersonalizzate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtMisurePersBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMisurePersBase As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMisurePersAltezza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMisurePersAltezza As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lnkCalcolaFormatoPersonalizzato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCalcolaFormatoPersonalizzato As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblMisurePersWrong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMisurePersWrong As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlOrientamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrientamento As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoCarta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoCarta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlColoreStampa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlColoreStampa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlFogliPagine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFogliPagine As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtLarghezza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLarghezza As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTBase As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProfondita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProfondita As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTProfondita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTProfondita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAltezza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAltezza As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTAltezza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTAltezza As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTipoQta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoQta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlQta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQtaUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtaUser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblQta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQtaCustom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtaCustom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rptOpzioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptOpzioni As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''tblDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDDL As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tableLav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableLav As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''btnCalcola control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalcola As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlErrore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlErrore As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblErroreMisure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErroreMisure As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInfoDim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoDim As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdoOpzioniPrezzo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoOpzioniPrezzo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rdoQuando control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoQuando As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''tblPrezzi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPrezzi As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblPrezzo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrezzo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkPreventivoPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPreventivoPDF As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblPrezzoConsigliato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrezzoConsigliato As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblColli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColli As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPeso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNomeLavoro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeLavoro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkVerificaFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVerificaFile As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lnkAddCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddCart As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkCompra1Click control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCompra1Click As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''PrevPromo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrevPromo As Global.FormerWeb.ucPrevPromo

    '''<summary>
    '''lnkAddCartRiepilogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddCartRiepilogo As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkDownloadModello3d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDownloadModello3d As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkCampGrat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCampGrat As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlPromo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPromo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptOmaggi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptOmaggi As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lbConsigliato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbConsigliato As Global.FormerWeb.ucLbConsigliato

    '''<summary>
    '''lbConsigliato1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbConsigliato1 As Global.FormerWeb.ucLbConsigliato

    '''<summary>
    '''lbConsigliato2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbConsigliato2 As Global.FormerWeb.ucLbConsigliato

    '''<summary>
    '''AggregateReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AggregateReview As Global.FormerWeb.ucAggregateReview

    '''<summary>
    '''rptReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptReview As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
End Class
