'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace GlsWS2
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://labelservice.gls-italy.com/", ConfigurationName:="GlsWS2.IlsWebServiceSoap")>  _
    Public Interface IlsWebServiceSoap
        
        'CODEGEN: Il parametro 'GetPdfResult' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="https://labelservice.gls-italy.com/GetPdf", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetPdf(ByVal request As GlsWS2.GetPdfRequest) As GlsWS2.GetPdfResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://labelservice.gls-italy.com/GetZpl", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetZpl(ByVal SedeGls As String, ByVal CodiceCliente As Integer, ByVal Password As String, ByVal CodiceContratto As Integer, ByVal ContatoreProgressivo As Long) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://labelservice.gls-italy.com/AddParcel", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AddParcel(ByVal XMLInfoParcel As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://labelservice.gls-italy.com/CloseWorkDay", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CloseWorkDay(ByVal XMLCloseInfoParcel As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://labelservice.gls-italy.com/DeleteSped", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DeleteSped(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String, ByVal NumSpedizione As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://labelservice.gls-italy.com/ListSped", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListSped(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://labelservice.gls-italy.com/ListSpedByStato", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListSpedByStato(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String, ByVal Stato As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://labelservice.gls-italy.com/ListSpedPeriod", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListSpedPeriod(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String, ByVal DataInizio As String, ByVal DataFine As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://labelservice.gls-italy.com/ListSpedPeriodByStato", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListSpedPeriodByStato(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String, ByVal DataInizio As String, ByVal DataFine As String, ByVal Stato As String) As System.Xml.XmlNode
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetPdf", WrapperNamespace:="https://labelservice.gls-italy.com/", IsWrapped:=true)>  _
    Partial Public Class GetPdfRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://labelservice.gls-italy.com/", Order:=0)>  _
        Public SedeGls As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://labelservice.gls-italy.com/", Order:=1)>  _
        Public CodiceCliente As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://labelservice.gls-italy.com/", Order:=2)>  _
        Public Password As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://labelservice.gls-italy.com/", Order:=3)>  _
        Public CodiceContratto As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://labelservice.gls-italy.com/", Order:=4)>  _
        Public ContatoreProgressivo As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SedeGls As String, ByVal CodiceCliente As Integer, ByVal Password As String, ByVal CodiceContratto As Integer, ByVal ContatoreProgressivo As Long)
            MyBase.New
            Me.SedeGls = SedeGls
            Me.CodiceCliente = CodiceCliente
            Me.Password = Password
            Me.CodiceContratto = CodiceContratto
            Me.ContatoreProgressivo = ContatoreProgressivo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetPdfResponse", WrapperNamespace:="https://labelservice.gls-italy.com/", IsWrapped:=true)>  _
    Partial Public Class GetPdfResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://labelservice.gls-italy.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public GetPdfResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetPdfResult() As Byte)
            MyBase.New
            Me.GetPdfResult = GetPdfResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IlsWebServiceSoapChannel
        Inherits GlsWS2.IlsWebServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class IlsWebServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of GlsWS2.IlsWebServiceSoap)
        Implements GlsWS2.IlsWebServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GlsWS2_IlsWebServiceSoap_GetPdf(ByVal request As GlsWS2.GetPdfRequest) As GlsWS2.GetPdfResponse Implements GlsWS2.IlsWebServiceSoap.GetPdf
            Return MyBase.Channel.GetPdf(request)
        End Function
        
        Public Function GetPdf(ByVal SedeGls As String, ByVal CodiceCliente As Integer, ByVal Password As String, ByVal CodiceContratto As Integer, ByVal ContatoreProgressivo As Long) As Byte()
            Dim inValue As GlsWS2.GetPdfRequest = New GlsWS2.GetPdfRequest()
            inValue.SedeGls = SedeGls
            inValue.CodiceCliente = CodiceCliente
            inValue.Password = Password
            inValue.CodiceContratto = CodiceContratto
            inValue.ContatoreProgressivo = ContatoreProgressivo
            Dim retVal As GlsWS2.GetPdfResponse = CType(Me,GlsWS2.IlsWebServiceSoap).GetPdf(inValue)
            Return retVal.GetPdfResult
        End Function
        
        Public Function GetZpl(ByVal SedeGls As String, ByVal CodiceCliente As Integer, ByVal Password As String, ByVal CodiceContratto As Integer, ByVal ContatoreProgressivo As Long) As System.Xml.XmlNode Implements GlsWS2.IlsWebServiceSoap.GetZpl
            Return MyBase.Channel.GetZpl(SedeGls, CodiceCliente, Password, CodiceContratto, ContatoreProgressivo)
        End Function
        
        Public Function AddParcel(ByVal XMLInfoParcel As String) As System.Xml.XmlNode Implements GlsWS2.IlsWebServiceSoap.AddParcel
            Return MyBase.Channel.AddParcel(XMLInfoParcel)
        End Function
        
        Public Function CloseWorkDay(ByVal XMLCloseInfoParcel As String) As System.Xml.XmlNode Implements GlsWS2.IlsWebServiceSoap.CloseWorkDay
            Return MyBase.Channel.CloseWorkDay(XMLCloseInfoParcel)
        End Function
        
        Public Function DeleteSped(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String, ByVal NumSpedizione As String) As System.Xml.XmlNode Implements GlsWS2.IlsWebServiceSoap.DeleteSped
            Return MyBase.Channel.DeleteSped(SedeGls, CodiceClienteGls, PasswordClienteGls, NumSpedizione)
        End Function
        
        Public Function ListSped(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String) As System.Xml.XmlNode Implements GlsWS2.IlsWebServiceSoap.ListSped
            Return MyBase.Channel.ListSped(SedeGls, CodiceClienteGls, PasswordClienteGls)
        End Function
        
        Public Function ListSpedByStato(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String, ByVal Stato As String) As System.Xml.XmlNode Implements GlsWS2.IlsWebServiceSoap.ListSpedByStato
            Return MyBase.Channel.ListSpedByStato(SedeGls, CodiceClienteGls, PasswordClienteGls, Stato)
        End Function
        
        Public Function ListSpedPeriod(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String, ByVal DataInizio As String, ByVal DataFine As String) As System.Xml.XmlNode Implements GlsWS2.IlsWebServiceSoap.ListSpedPeriod
            Return MyBase.Channel.ListSpedPeriod(SedeGls, CodiceClienteGls, PasswordClienteGls, DataInizio, DataFine)
        End Function
        
        Public Function ListSpedPeriodByStato(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String, ByVal DataInizio As String, ByVal DataFine As String, ByVal Stato As String) As System.Xml.XmlNode Implements GlsWS2.IlsWebServiceSoap.ListSpedPeriodByStato
            Return MyBase.Channel.ListSpedPeriodByStato(SedeGls, CodiceClienteGls, PasswordClienteGls, DataInizio, DataFine, Stato)
        End Function
    End Class
End Namespace
