'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucPreventivazioni

    '''<summary>
    '''rptOfferte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptOfferte As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptCatVirtuali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCatVirtuali As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptPreventivazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPreventivazione As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptPackaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPackaging As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptDigitale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptDigitale As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptRicamo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptRicamo As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptEtichette control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptEtichette As Global.System.Web.UI.WebControls.Repeater
End Class
