'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace GlsCheckAddress
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://checkaddress.gls-italy.com/", ConfigurationName:="GlsCheckAddress.wsCheckAddressSoap")>  _
    Public Interface wsCheckAddressSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://checkaddress.gls-italy.com/CheckAddress", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckAddress(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String, ByVal SiglaProvincia As String, ByVal Cap As String, ByVal Localita As String, ByVal Indirizzo As String) As System.Xml.XmlNode
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsCheckAddressSoapChannel
        Inherits GlsCheckAddress.wsCheckAddressSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsCheckAddressSoapClient
        Inherits System.ServiceModel.ClientBase(Of GlsCheckAddress.wsCheckAddressSoap)
        Implements GlsCheckAddress.wsCheckAddressSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CheckAddress(ByVal SedeGls As String, ByVal CodiceClienteGls As String, ByVal PasswordClienteGls As String, ByVal SiglaProvincia As String, ByVal Cap As String, ByVal Localita As String, ByVal Indirizzo As String) As System.Xml.XmlNode Implements GlsCheckAddress.wsCheckAddressSoap.CheckAddress
            Return MyBase.Channel.CheckAddress(SedeGls, CodiceClienteGls, PasswordClienteGls, SiglaProvincia, Cap, Localita, Indirizzo)
        End Function
    End Class
End Namespace
