'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pDettaglioOrdine

    '''<summary>
    '''IframeDetaglioOrdini control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IframeDetaglioOrdini As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rptOrdini control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptOrdini As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlPagamentoEffettuato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPagamentoEffettuato As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPagamentoEffettuato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPagamentoEffettuato As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlPagamAnticip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPagamAnticip As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnPayBancaSella control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPayBancaSella As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblNoDocFisc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoDocFisc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDocFiscDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocFiscDownload As Global.System.Web.UI.WebControls.LinkButton
End Class
